/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Workflows;

import Business.EcoSystem;
import Business.LookUpMapping;
import Business.UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author architnigam
 */
public class ChatBotSymptomsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChatBotSymptomsJPanel
     */
    UserAccount userAccount;
    EcoSystem system;
    public ChatBotSymptomsJPanel(UserAccount userAccount, EcoSystem system) {
        initComponents();
        this.userAccount = userAccount;
        this.system = system;
        
        ButtonGroup diabetesBtnGroup = new ButtonGroup();
        diabetesBtnGroup.add(diabetesYes);
        diabetesBtnGroup.add(diabetesNo);
        
        ButtonGroup bpGroup = new ButtonGroup();
        bpGroup.add(BPNo);
        bpGroup.add(BPYes);
        
        ButtonGroup chemoGroup = new ButtonGroup();
        chemoGroup.add(chemoNo);
        chemoGroup.add(chemoYes);
        
        ButtonGroup splGroup = new ButtonGroup();
        splGroup.add(splNo);
        splGroup.add(splYes);
        
        txtSymptom1.setEditable(false);
        txtSymptom2.setEditable(false);
        txtSymptom3.setEditable(false);
        
        if(!(  txtSymptom1.getText().equals("") && txtSymptom2.getText().equals("") && txtSymptom3.getText().equals("")))
         {
                btnAddSymptom.setEnabled(false);
          }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnAddSymptom = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BPYes = new javax.swing.JRadioButton();
        diabetesNo = new javax.swing.JRadioButton();
        diabetesYes = new javax.swing.JRadioButton();
        BPNo = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtSymptom1 = new javax.swing.JTextField();
        txtSymptom2 = new javax.swing.JTextField();
        txtSymptom3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        chemoYes = new javax.swing.JRadioButton();
        chemoNo = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        splYes = new javax.swing.JRadioButton();
        splNo = new javax.swing.JRadioButton();
        btnEvaulateSymptom = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        jLabel1.setText("Welcome to Disease Catcher!");
        add(jLabel1);
        jLabel1.setBounds(10, 30, 570, 70);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Headache", "Body Pain", "Fever", "Cold", "Cough", "Abnormal Heart Rate", "Dizziness", "Breathlessness", "Loss of taste", "Loss of smell" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 180, 240, 170);

        btnAddSymptom.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnAddSymptom.setText("Add Symptoms");
        btnAddSymptom.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddSymptom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSymptomActionPerformed(evt);
            }
        });
        btnAddSymptom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAddSymptomKeyPressed(evt);
            }
        });
        add(btnAddSymptom);
        btnAddSymptom.setBounds(50, 370, 130, 30);

        jLabel2.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel2.setText("Does the patient have diabetes?");
        add(jLabel2);
        jLabel2.setBounds(30, 430, 250, 20);

        jLabel3.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel3.setText("Does the patient have history of high blood pressure?");
        add(jLabel3);
        jLabel3.setBounds(30, 500, 380, 20);

        BPYes.setText("Yes");
        add(BPYes);
        BPYes.setBounds(430, 500, 54, 23);

        diabetesNo.setText("No");
        diabetesNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diabetesNoActionPerformed(evt);
            }
        });
        add(diabetesNo);
        diabetesNo.setBounds(520, 430, 50, 23);

        diabetesYes.setText("Yes");
        diabetesYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diabetesYesActionPerformed(evt);
            }
        });
        add(diabetesYes);
        diabetesYes.setBounds(430, 430, 54, 23);

        BPNo.setText("No");
        BPNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPNoActionPerformed(evt);
            }
        });
        add(BPNo);
        BPNo.setBounds(520, 500, 50, 23);

        jLabel4.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel4.setText("Symptom 1: ");
        add(jLabel4);
        jLabel4.setBounds(320, 190, 110, 20);
        add(txtSymptom1);
        txtSymptom1.setBounds(450, 190, 113, 26);
        add(txtSymptom2);
        txtSymptom2.setBounds(450, 230, 113, 26);
        add(txtSymptom3);
        txtSymptom3.setBounds(450, 290, 113, 26);

        jLabel5.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel5.setText("Symptom 2: ");
        add(jLabel5);
        jLabel5.setBounds(320, 240, 110, 20);

        jLabel6.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel6.setText("Symptom 3:");
        add(jLabel6);
        jLabel6.setBounds(330, 300, 110, 20);

        jLabel7.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel7.setText("Is the patient undergoing chemotherapy?");
        add(jLabel7);
        jLabel7.setBounds(40, 570, 300, 20);

        chemoYes.setText("Yes");
        add(chemoYes);
        chemoYes.setBounds(430, 560, 54, 23);

        chemoNo.setText("No");
        chemoNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chemoNoActionPerformed(evt);
            }
        });
        add(chemoNo);
        chemoNo.setBounds(520, 560, 50, 23);

        jLabel8.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel8.setText("Does patient have Parkinson's or Alzheimer's disease?");
        add(jLabel8);
        jLabel8.setBounds(40, 630, 380, 20);

        splYes.setText("Yes");
        add(splYes);
        splYes.setBounds(440, 620, 54, 23);

        splNo.setText("No");
        splNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                splNoActionPerformed(evt);
            }
        });
        add(splNo);
        splNo.setBounds(530, 620, 50, 23);

        btnEvaulateSymptom.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnEvaulateSymptom.setText("Evaluate Symptoms");
        btnEvaulateSymptom.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEvaulateSymptom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaulateSymptomActionPerformed(evt);
            }
        });
        add(btnEvaulateSymptom);
        btnEvaulateSymptom.setBounds(276, 691, 190, 40);

        jLabel9.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel9.setText("Select maximum 3 symptoms: ");
        add(jLabel9);
        jLabel9.setBounds(40, 130, 230, 20);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/robot.jpeg"))); // NOI18N
        jLabel10.setText("jLabel10");
        add(jLabel10);
        jLabel10.setBounds(600, 10, 350, 260);
    }// </editor-fold>//GEN-END:initComponents

    private void diabetesNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diabetesNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diabetesNoActionPerformed

    private void BPNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BPNoActionPerformed

    private void chemoNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chemoNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chemoNoActionPerformed

    private void splNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_splNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_splNoActionPerformed

    private void btnAddSymptomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSymptomActionPerformed
        // TODO add your handling code here:
        int selectedIndex = jList1.getSelectedIndex();
        if(selectedIndex < 0)
        {
            
        }
        else{
            String selectedValue = jList1.getSelectedValue();
            if( (txtSymptom1.getText().equals("") && txtSymptom2.getText().equals("") 
                    && txtSymptom3.getText().equals("")))
            {
                txtSymptom1.setText(selectedValue);
            }
            else if(!(txtSymptom1.getText().equals("")) 
                    && txtSymptom2.getText().equals("") && txtSymptom3.getText().equals(""))
            {
                txtSymptom2.setText(selectedValue);
            }
            else if(!(txtSymptom1.getText().equals("")) && !(txtSymptom2.getText().equals("")))
            {
                txtSymptom3.setText(selectedValue);
            }
        }
        
        
    }//GEN-LAST:event_btnAddSymptomActionPerformed

    private void btnAddSymptomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAddSymptomKeyPressed
        // TODO add your handling code here:
        int counterClick = 0;
        counterClick++;
        
        if(counterClick == 3)
        {
            btnAddSymptom.setEnabled(false);
        }
    }//GEN-LAST:event_btnAddSymptomKeyPressed

    private void btnEvaulateSymptomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvaulateSymptomActionPerformed
        // TODO add your handling code here:
        ArrayList<Integer> listOfSymptoms = new ArrayList<Integer>();
        String symptom1Value = txtSymptom1.getText();
        String symptom2Value = txtSymptom2.getText();
        String symptom3Value = txtSymptom3.getText();
        LookUpMapping lookups = new LookUpMapping();
        int symptom1 = lookups.mapSymptoms(symptom1Value);
        int symptom2 = lookups.mapSymptoms(symptom2Value);
        int symptom3 = lookups.mapSymptoms(symptom3Value);
        listOfSymptoms.add(symptom1);
        listOfSymptoms.add(symptom2);
        listOfSymptoms.add(symptom3);
        
        if(listOfSymptoms.contains(0) && listOfSymptoms.contains(1) && listOfSymptoms.contains(2))
        {
            JOptionPane.showMessageDialog(this, "Symptom Catcher Analysis: \n"
                    + "\nPatient might be suffering from the following: \n-  Flu"
                    + "\nIt is advised that the patient wear a mask if stepping outdoors and take "
                    + "prescribed medications\nAlert Level: Moderate");
        }
        else if(listOfSymptoms.contains(0) && listOfSymptoms.contains(2) && listOfSymptoms.contains(3))
        {
            JOptionPane.showMessageDialog(this, "Symptom Catcher Analysis: \n"
                    + "\nPatient might be suffering from the following: \n- Allergies"
                    + "\nIt is advised that the patient wear a mask if stepping outdoors and take "
                    + "prescribed medications\nAlert Level: Moderate");
        }
        else if(listOfSymptoms.contains(0) && listOfSymptoms.contains(1) && listOfSymptoms.contains(6))
        {
            JOptionPane.showMessageDialog(this, "Symptom Catcher Analysis: \n"
                    + "\nPatient might be suffering from the following: \n - Migraine"
                    + "\nIt is advised that the patient wear a mask if stepping outdoors and take "
                    + "prescribed medications\nAlert Level: Critical");
        }
        else if(listOfSymptoms.contains(7) && listOfSymptoms.contains(8))
        {
            JOptionPane.showMessageDialog(this, "Symptom Catcher Analysis: \n"
                    + "\nPatient might be suffering from the following: \n- COVID-19"
                    + "\nIt is advised that the patient wear a mask if stepping outdoors and take "
                    + "schedule a COVID-19 test ASAP.\nAlert Level: Extremely Critical");
        }
    }//GEN-LAST:event_btnEvaulateSymptomActionPerformed

    private void diabetesYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diabetesYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diabetesYesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BPNo;
    private javax.swing.JRadioButton BPYes;
    private javax.swing.JButton btnAddSymptom;
    private javax.swing.JButton btnEvaulateSymptom;
    private javax.swing.JRadioButton chemoNo;
    private javax.swing.JRadioButton chemoYes;
    private javax.swing.JRadioButton diabetesNo;
    private javax.swing.JRadioButton diabetesYes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton splNo;
    private javax.swing.JRadioButton splYes;
    private javax.swing.JTextField txtSymptom1;
    private javax.swing.JTextField txtSymptom2;
    private javax.swing.JTextField txtSymptom3;
    // End of variables declaration//GEN-END:variables
}
