/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Workflows;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import javax.swing.ButtonGroup;

/**
 *
 * @author architnigam
 */
public class ChatBotSymptomsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChatBotSymptomsJPanel
     */
    UserAccount userAccount;
    EcoSystem system;
    public ChatBotSymptomsJPanel(UserAccount userAccount, EcoSystem system) {
        initComponents();
        this.userAccount = userAccount;
        this.system = system;
        
        ButtonGroup diabetesBtnGroup = new ButtonGroup();
        diabetesBtnGroup.add(diabetesYes);
        diabetesBtnGroup.add(diabetesNo);
        
        ButtonGroup bpGroup = new ButtonGroup();
        bpGroup.add(BPNo);
        bpGroup.add(BPYes);
        
        ButtonGroup chemoGroup = new ButtonGroup();
        chemoGroup.add(chemoNo);
        chemoGroup.add(chemoYes);
        
        ButtonGroup splGroup = new ButtonGroup();
        splGroup.add(splNo);
        splGroup.add(splYes);
        
        txtSymptom1.setEditable(false);
        txtSymptom2.setEditable(false);
        txtSymptom3.setEditable(false);
        
        if(!(  txtSymptom1.getText().equals("") && txtSymptom2.getText().equals("") && txtSymptom3.getText().equals("")))
         {
                btnAddSymptom.setEnabled(false);
          }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnAddSymptom = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BPYes = new javax.swing.JRadioButton();
        diabetesNo = new javax.swing.JRadioButton();
        diabetesYes = new javax.swing.JRadioButton();
        BPNo = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtSymptom1 = new javax.swing.JTextField();
        txtSymptom2 = new javax.swing.JTextField();
        txtSymptom3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        chemoYes = new javax.swing.JRadioButton();
        chemoNo = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        splYes = new javax.swing.JRadioButton();
        splNo = new javax.swing.JRadioButton();
        btnEvaulateSymptom = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("WELCOME TO SYMPTOMS CATCHER ");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Headache", "Body Pain", "Fever", "Cold", "Cough", "Abnormal Heart Rate", "Dizziness", "Breathlessness" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        btnAddSymptom.setText("Add Symptoms");
        btnAddSymptom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSymptomActionPerformed(evt);
            }
        });
        btnAddSymptom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAddSymptomKeyPressed(evt);
            }
        });

        jLabel2.setText("Does the patient have diabetes?");

        jLabel3.setText("Does the patient have history of high blood pressure?");

        BPYes.setText("Yes");

        diabetesNo.setText("No");
        diabetesNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diabetesNoActionPerformed(evt);
            }
        });

        diabetesYes.setText("Yes");

        BPNo.setText("No");
        BPNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPNoActionPerformed(evt);
            }
        });

        jLabel4.setText("Symptom 1: ");

        jLabel5.setText("Symptom 2: ");

        jLabel6.setText("Symptom 3:");

        jLabel7.setText("Is the patient undergoing chemotherapy?");

        chemoYes.setText("Yes");

        chemoNo.setText("No");
        chemoNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chemoNoActionPerformed(evt);
            }
        });

        jLabel8.setText("Does patient have Parkinson's or Alzheimer's disease?");

        splYes.setText("Yes");

        splNo.setText("No");
        splNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                splNoActionPerformed(evt);
            }
        });

        btnEvaulateSymptom.setText("Evaluate Symptoms");

        jLabel9.setText("Select maximum 3 symptoms: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(diabetesYes)
                                        .addGap(18, 18, 18)
                                        .addComponent(diabetesNo)))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSymptom2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSymptom3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSymptom1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnAddSymptom))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(chemoYes))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BPYes)
                                        .addGap(18, 18, 18)
                                        .addComponent(BPNo))
                                    .addComponent(chemoNo)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(splYes)
                                .addGap(18, 18, 18)
                                .addComponent(splNo))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(btnEvaulateSymptom, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(375, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSymptom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtSymptom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtSymptom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addComponent(btnAddSymptom)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(diabetesYes)
                    .addComponent(diabetesNo))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BPYes)
                    .addComponent(BPNo))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(chemoYes)
                    .addComponent(chemoNo))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(splYes)
                    .addComponent(splNo))
                .addGap(47, 47, 47)
                .addComponent(btnEvaulateSymptom)
                .addContainerGap(112, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void diabetesNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diabetesNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diabetesNoActionPerformed

    private void BPNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BPNoActionPerformed

    private void chemoNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chemoNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chemoNoActionPerformed

    private void splNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_splNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_splNoActionPerformed

    private void btnAddSymptomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSymptomActionPerformed
        // TODO add your handling code here:
        int selectedIndex = jList1.getSelectedIndex();
        if(selectedIndex < 0)
        {
            
        }
        else{
            String selectedValue = jList1.getSelectedValue();
            if( (txtSymptom1.getText().equals("") && txtSymptom2.getText().equals("") 
                    && txtSymptom3.getText().equals("")))
            {
                txtSymptom1.setText(selectedValue);
            }
            else if(!(txtSymptom1.getText().equals("")) 
                    && txtSymptom2.getText().equals("") && txtSymptom3.getText().equals(""))
            {
                txtSymptom2.setText(selectedValue);
            }
            else if(!(txtSymptom1.getText().equals("")) && !(txtSymptom2.getText().equals("")))
            {
                txtSymptom3.setText(selectedValue);
            }
        }
        
        
    }//GEN-LAST:event_btnAddSymptomActionPerformed

    private void btnAddSymptomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAddSymptomKeyPressed
        // TODO add your handling code here:
        int counterClick = 0;
        counterClick++;
        
        if(counterClick == 3)
        {
            btnAddSymptom.setEnabled(false);
        }
    }//GEN-LAST:event_btnAddSymptomKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BPNo;
    private javax.swing.JRadioButton BPYes;
    private javax.swing.JButton btnAddSymptom;
    private javax.swing.JButton btnEvaulateSymptom;
    private javax.swing.JRadioButton chemoNo;
    private javax.swing.JRadioButton chemoYes;
    private javax.swing.JRadioButton diabetesNo;
    private javax.swing.JRadioButton diabetesYes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton splNo;
    private javax.swing.JRadioButton splYes;
    private javax.swing.JTextField txtSymptom1;
    private javax.swing.JTextField txtSymptom2;
    private javax.swing.JTextField txtSymptom3;
    // End of variables declaration//GEN-END:variables
}
