/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Appointments;

import Business.Appointments.Appointment;
import Business.Counsellors.Counsellor;
import Business.EcoSystem;
import Business.LookUpMapping;
import Business.Providers.Provider;
import Business.UserAccount.UserAccount;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author architnigam
 */

public class ManageAppointmentsCounsellorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAppointmentsCounsellorJPanel
     */
    UserAccount userAccount;
    EcoSystem system;
    public ManageAppointmentsCounsellorJPanel(UserAccount userAccount, EcoSystem system) {
        initComponents();
        this.userAccount = userAccount;
        this.system = system;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAppointments = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        cbAppointmentCompleted = new javax.swing.JCheckBox();
        txtComments = new javax.swing.JTextField();
        lblComments = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 20)); // NOI18N
        jLabel1.setText("Appointments Scheduled");

        tblAppointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Appointment ID", "Patient Name", "Status", "Reason", "Appointment Time", "Appointment"
            }
        ));
        jScrollPane1.setViewportView(tblAppointments);

        btnUpdate.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        cbAppointmentCompleted.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        cbAppointmentCompleted.setText("Appointment completed?");

        lblComments.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lblComments.setText("Comments:");

        btnSave.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(cbAppointmentCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(lblComments)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(txtComments, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(370, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(cbAppointmentCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtComments, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblComments))
                .addGap(32, 32, 32)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblAppointments.getSelectedRow();
        LookUpMapping lookups = new LookUpMapping();
        DefaultTableModel model = (DefaultTableModel) tblAppointments.getModel();
        Appointment selectedAppointment = (Appointment) model.getValueAt(selectedIndex, 5);
        if(selectedAppointment.getAppointmentStatus() == 0)
        {
            btnSave.setVisible(false);
            txtComments.setVisible(false);
            lblComments.setVisible(false);
            cbAppointmentCompleted.setVisible(false);
        }
        else{
            String appointmentStatusValue = lookups.mapAppointmentStatus(selectedAppointment.getAppointmentStatus());
            JOptionPane.showMessageDialog(this, "An appointment with status '"+appointmentStatusValue+"' cannot be updated");
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblAppointments.getSelectedRow();
        if(selectedIndex < 0)
        {
            JOptionPane.showMessageDialog(this, "Please select an appointment before proceding!");
        }
        else{
            DefaultTableModel model = (DefaultTableModel) tblAppointments.getModel();
            Appointment selectedAppointment = (Appointment) model.getValueAt(selectedIndex, 5);
            Appointment updatedAppointment = system.getAppointmentDirectory().updateAppointment(selectedAppointment);
            if(cbAppointmentCompleted.isSelected())
            {
                updatedAppointment.setAppointmentStatus(1);
                updatedAppointment.setAppointmentClosingComments(txtComments.getText());
            }
            cbAppointmentCompleted.setVisible(false);
            btnSave.setVisible(false);
            txtComments.setVisible(false);
            lblComments.setVisible(false);
            JOptionPane.showMessageDialog(this, "Appointment successfully closed!");
            populateTable();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblAppointments.getSelectedRow();
        LookUpMapping lookups = new LookUpMapping();
        DefaultTableModel model = (DefaultTableModel) tblAppointments.getModel();
        Appointment selectedAppointment = (Appointment) model.getValueAt(selectedIndex, 5);
        if(selectedAppointment.getAppointmentStatus() == 0)
        {
            Appointment updatedAppointment = system.getAppointmentDirectory().updateAppointment(selectedAppointment);
            updatedAppointment.setAppointmentStatus(2);
            updatedAppointment.setAppointmentClosingComments("Canceled");
        }
        else{
            String appointmentStatusValue = lookups.mapAppointmentStatus(selectedAppointment.getAppointmentStatus());
            JOptionPane.showMessageDialog(this, "An appointment with status '"+appointmentStatusValue+"' cannot be canceled");
        }
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox cbAppointmentCompleted;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblComments;
    private javax.swing.JTable tblAppointments;
    private javax.swing.JTextField txtComments;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model1 = (DefaultTableModel) tblAppointments.getModel();
        LookUpMapping lookups = new LookUpMapping();
        Counsellor counsellor = system.getCounsellorDirectory().findCounsellorByEmailID(userAccount.getUsername(), 
                 system.getCounsellorDirectory().getListOfCounsellors());
        model1.setRowCount(0);
        for(int index = 0; index < system.getAppointmentDirectory().getListOfAppointments().size(); index++)
        {
            Object[] row = new Object[6];
            Appointment currentAppointment = system.getAppointmentDirectory().getListOfAppointments().get(index);
            if(currentAppointment.getAppointmentCounsellor().getCounsellorID().equals(
            counsellor.getCounsellorID()))
            {
                row[0] = currentAppointment.getAppointmentID();
                row[1] = currentAppointment.getAppointmentPatient().getPatientName();
                row[2] = lookups.mapAppointmentStatus(currentAppointment.getAppointmentStatus());
                row[3] = currentAppointment.getAppointmentReason();
                DateFormat df = new SimpleDateFormat("MM/dd/yyyy");
                String dateToString = df.format(currentAppointment.getAppointmentDate()).substring(0, 10); 
                row[4] = dateToString + " " + currentAppointment.getAppointmentTime();
                row[5] = currentAppointment;
            }
            model1.addRow(row);
        }
    }
}
