/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientRole;

import Business.EcoSystem;

import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.Workflows.ChatBotSymptomsJPanel;
import userinterface.Alerts.CreateAnAlertJPanel;
import userinterface.Appointments.ScheduleACOVIDTestAppointment;
import userinterface.Appointments.ScheduleAppointmentJPanel;
import userinterface.Forms.COVIDSelfDiagnosisFormJPanel;
import userinterface.Workflows.ViewPatientInformationJPanel;

/**
 *
 * @author nishitasheelendraupadhyay
 */
public class PatientAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    EcoSystem system;
    private UserAccount userAccount;
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public PatientAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system ) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.userAccount = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnViewPatientDetails = new javax.swing.JButton();
        btnSelfDiagnosisForm = new javax.swing.JButton();
        btnAppointment = new javax.swing.JButton();
        btnAlert = new javax.swing.JButton();
        btnSymptomCatcher = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(246, 233, 244));

        btnViewPatientDetails.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnViewPatientDetails.setText("View My Details");
        btnViewPatientDetails.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewPatientDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPatientDetailsActionPerformed(evt);
            }
        });

        btnSelfDiagnosisForm.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnSelfDiagnosisForm.setText("Fill Self Diagnosis Form");
        btnSelfDiagnosisForm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSelfDiagnosisForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelfDiagnosisFormActionPerformed(evt);
            }
        });

        btnAppointment.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnAppointment.setText("Schedule an Appointment");
        btnAppointment.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppointmentActionPerformed(evt);
            }
        });

        btnAlert.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnAlert.setText("Create an Alert");
        btnAlert.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAlert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlertActionPerformed(evt);
            }
        });

        btnSymptomCatcher.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnSymptomCatcher.setText("Chat with SymptomCatcher!");
        btnSymptomCatcher.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSymptomCatcher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSymptomCatcherActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jButton1.setText("Schedule a COVID-19 Test");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnSymptomCatcher, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnAlert, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAppointment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnSelfDiagnosisForm, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnViewPatientDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(btnViewPatientDetails)
                .addGap(42, 42, 42)
                .addComponent(btnSelfDiagnosisForm)
                .addGap(51, 51, 51)
                .addComponent(btnAppointment)
                .addGap(58, 58, 58)
                .addComponent(btnAlert)
                .addGap(54, 54, 54)
                .addComponent(btnSymptomCatcher)
                .addGap(56, 56, 56)
                .addComponent(jButton1)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 923, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 879, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSymptomCatcherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSymptomCatcherActionPerformed
        // TODO add your handling code here:
        ChatBotSymptomsJPanel chatBotSymptomsPanel = new ChatBotSymptomsJPanel(userAccount, system);
        jSplitPane1.setRightComponent(chatBotSymptomsPanel);
    }//GEN-LAST:event_btnSymptomCatcherActionPerformed

    private void btnSelfDiagnosisFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelfDiagnosisFormActionPerformed
        // TODO add your handling code here:
        try{
            COVIDSelfDiagnosisFormJPanel selfDiagnosisFormJPanel = new COVIDSelfDiagnosisFormJPanel(userAccount, system);
            jSplitPane1.setRightComponent(selfDiagnosisFormJPanel);
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
                
    }//GEN-LAST:event_btnSelfDiagnosisFormActionPerformed

    private void btnAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointmentActionPerformed
        // TODO add your handling code here:
        ScheduleAppointmentJPanel scheduleAppointmentJPanel = new ScheduleAppointmentJPanel(system, userAccount);
        jSplitPane1.setRightComponent(scheduleAppointmentJPanel);
    }//GEN-LAST:event_btnAppointmentActionPerformed

    private void btnAlertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlertActionPerformed
        // TODO add your handling code here:
        CreateAnAlertJPanel createAnAlertJPanel = new CreateAnAlertJPanel(userAccount,system );
        jSplitPane1.setRightComponent(createAnAlertJPanel);
    }//GEN-LAST:event_btnAlertActionPerformed

    private void btnViewPatientDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPatientDetailsActionPerformed
        // TODO add your handling code here:
        ViewPatientInformationJPanel viewPatientInformationPanel = new ViewPatientInformationJPanel(userAccount, system, "Own");
        jSplitPane1.setRightComponent(viewPatientInformationPanel);
    }//GEN-LAST:event_btnViewPatientDetailsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ScheduleACOVIDTestAppointment scheduleCOVIDTest = new ScheduleACOVIDTestAppointment(userAccount,system);
        jSplitPane1.setRightComponent(scheduleCOVIDTest);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlert;
    private javax.swing.JButton btnAppointment;
    private javax.swing.JButton btnSelfDiagnosisForm;
    private javax.swing.JButton btnSymptomCatcher;
    private javax.swing.JButton btnViewPatientDetails;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
