/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Forms;

import Business.EcoSystem;
import Business.Forms.COVIDSelfDiagnosisForm;
import Business.Patients.Patient;
import Business.UserAccount.UserAccount;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author architnigam
 */
public class COVIDSelfDiagnosisFormJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SelfDiagnosisJPanel
     */
    private UserAccount userAccount;
    private EcoSystem system;
    Patient patientLoggedIn;
    public COVIDSelfDiagnosisFormJPanel(UserAccount userAccount, EcoSystem system) throws ParseException {
        initComponents();
        this.userAccount = userAccount;
        this.system = system;
        patientLoggedIn = system.getPatientDirectory().findPatientByEmailID(userAccount.getUsername(), 
                system.getPatientDirectory().getPatientList());
        
        txtName.setText(patientLoggedIn.getPatientName());
        txtName.setEditable(false);
        
        txtSignatureName.setText(patientLoggedIn.getPatientName());
        txtSignatureName.setEditable(false);
        
        txtMRN.setText(patientLoggedIn.getPatientMRN());
        txtMRN.setEditable(false);
        
        DateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
        Date todayDate = new Date();
        Date todayDateWithZeroTime = formatter.parse(formatter.format(todayDate)); 
        String dateToString = formatter.format(todayDateWithZeroTime); 
        dateToString = dateToString.substring(0, 10);
        txtTodayDate.setText(String.valueOf(dateToString));
        txtTodayDate.setEditable(false);
        
        ButtonGroup group1 = new ButtonGroup();
        group1.add(rbQOneNo);
        group1.add(rbQOneYes); 
        
        ButtonGroup group2 = new ButtonGroup();
        group2.add(rbQTwoNo);
        group2.add(rbQTwoYes); 
        
        ButtonGroup group3 = new ButtonGroup();
        group3.add(rbQThreeNo);
        group3.add(rbQThreeYes); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeading = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblLocation = new javax.swing.JLabel();
        txtMRN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rbQOneYes = new javax.swing.JRadioButton();
        rbQOneNo = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rbQTwoYes = new javax.swing.JRadioButton();
        rbQTwoNo = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rbQThreeYes = new javax.swing.JRadioButton();
        rbQThreeNo = new javax.swing.JRadioButton();
        lblConditions = new javax.swing.JLabel();
        cbAgreeTermsAndConditions = new javax.swing.JCheckBox();
        txtSignatureName = new javax.swing.JTextField();
        lblSignatureName = new javax.swing.JLabel();
        lblSignatureDate = new javax.swing.JLabel();
        btnSubmitForm = new javax.swing.JButton();
        txtTodayDate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(null);

        lblHeading.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblHeading.setText("CORONAVIRUS SELF ASSESSMENT FORM");
        add(lblHeading);
        lblHeading.setBounds(182, 52, 365, 41);

        lblName.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lblName.setText("Name: ");
        add(lblName);
        lblName.setBounds(136, 162, 47, 15);
        add(txtName);
        txtName.setBounds(236, 155, 155, 26);

        lblLocation.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lblLocation.setText("MRN:");
        add(lblLocation);
        lblLocation.setBounds(136, 236, 37, 15);
        add(txtMRN);
        txtMRN.setBounds(236, 229, 155, 26);

        jLabel3.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel3.setText("Have you been to one of the COVID-19 affected countries in the last 14 days?");
        add(jLabel3);
        jLabel3.setBounds(6, 304, 530, 23);

        rbQOneYes.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        rbQOneYes.setText("Yes");
        add(rbQOneYes);
        rbQOneYes.setBounds(542, 303, 67, 23);

        rbQOneNo.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        rbQOneNo.setText("No");
        add(rbQOneNo);
        rbQOneNo.setBounds(627, 303, 72, 23);

        jLabel4.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel4.setText("Have you been in close contact with a confirmed case of coronavirus? ");
        add(jLabel4);
        jLabel4.setBounds(40, 373, 487, 15);

        rbQTwoYes.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        rbQTwoYes.setText("Yes");
        add(rbQTwoYes);
        rbQTwoYes.setBounds(542, 368, 67, 23);

        rbQTwoNo.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        rbQTwoNo.setText("No");
        add(rbQTwoNo);
        rbQTwoNo.setBounds(627, 368, 72, 23);

        jLabel5.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel5.setText("Are you currently experiencing symptoms (cough, shortness of breath, fever)");
        add(jLabel5);
        jLabel5.setBounds(0, 443, 529, 15);

        rbQThreeYes.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        rbQThreeYes.setText("Yes");
        add(rbQThreeYes);
        rbQThreeYes.setBounds(562, 438, 67, 23);

        rbQThreeNo.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        rbQThreeNo.setText("No");
        add(rbQThreeNo);
        rbQThreeNo.setBounds(647, 438, 72, 23);

        lblConditions.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lblConditions.setText("By submitting I hereby confirm that the information I have given above is true, and that I will comply with the terms and conditions outlined above. ");
        add(lblConditions);
        lblConditions.setBounds(6, 479, 955, 114);

        cbAgreeTermsAndConditions.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        cbAgreeTermsAndConditions.setText("I agree to terms & conditions. * ");
        add(cbAgreeTermsAndConditions);
        cbAgreeTermsAndConditions.setBounds(32, 605, 303, 34);
        add(txtSignatureName);
        txtSignatureName.setBounds(97, 664, 146, 34);

        lblSignatureName.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lblSignatureName.setText("Name: ");
        add(lblSignatureName);
        lblSignatureName.setBounds(32, 675, 47, 15);

        lblSignatureDate.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lblSignatureDate.setText("Today's Date: ");
        add(lblSignatureDate);
        lblSignatureDate.setBounds(289, 665, 98, 34);

        btnSubmitForm.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnSubmitForm.setText("Submit COVID-19 Self Diagnosis Form");
        btnSubmitForm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmitForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitFormActionPerformed(evt);
            }
        });
        add(btnSubmitForm);
        btnSubmitForm.setBounds(137, 761, 402, 38);
        add(txtTodayDate);
        txtTodayDate.setBounds(399, 664, 232, 34);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/COVID.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jLabel9.setPreferredSize(new java.awt.Dimension(116, 109));
        add(jLabel9);
        jLabel9.setBounds(20, 20, 116, 109);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitFormActionPerformed
        // TODO add your handling code here:
        boolean hasPatientTraveledAbroad = false;
        boolean hasPatientBeenInContactWithPositivePatient= false;
        boolean isPatientExperiencingSymptoms= false;
        boolean hasPatientAgreedTAndC= false;
        
        if(rbQOneNo.isSelected())
        {
            hasPatientTraveledAbroad = false;
        }
        else if(rbQOneYes.isSelected())
        {
            hasPatientTraveledAbroad = true;
        }
        
        if(rbQTwoNo.isSelected())
        {
            hasPatientBeenInContactWithPositivePatient = false;
        }
        else if(rbQTwoYes.isSelected())
        {
            hasPatientBeenInContactWithPositivePatient = true;
        }
        
        if(rbQThreeNo.isSelected())
        {
            isPatientExperiencingSymptoms = false;
        }
        else if(rbQThreeYes.isSelected())
        {
            isPatientExperiencingSymptoms = true;
        }
        
        if(cbAgreeTermsAndConditions.isSelected())
        {
            hasPatientAgreedTAndC = true;
        }
        else{
            hasPatientAgreedTAndC = false;
        }
        
        
        if(hasPatientAgreedTAndC)
        {
            for(int index = 0; index < system.getCovidFormsDirectory().getListOfCOVIDForms().size(); index++)
            {
               try{
                    Date todayDate = new Date();
                DateFormat formatter = new SimpleDateFormat("MM/dd/yyyy"); 
                String dateToString = formatter.format(todayDate); 
                dateToString = dateToString.substring(0, 10);
                Date todaysDate =new SimpleDateFormat("MM/dd/yyyy").parse(dateToString);
                COVIDSelfDiagnosisForm currentCOVIDForm = system.getCovidFormsDirectory().getListOfCOVIDForms().get(index);
                if(currentCOVIDForm.getPatientFillingForm().getPatientMRN().equals(patientLoggedIn.getPatientMRN()))
                {
                    if(currentCOVIDForm.getDateOfForm().equals(todaysDate))
                    {
                        JOptionPane.showMessageDialog(this, "COVID - 19 self assessment already submitted for today!");
                    }
                    else{
                        try{
                        COVIDSelfDiagnosisForm newCOVIDForm = system.getCovidFormsDirectory().createCOVIDSelfDiagnosisForm(patientLoggedIn, 
                                hasPatientTraveledAbroad, hasPatientBeenInContactWithPositivePatient, isPatientExperiencingSymptoms, 
                                hasPatientAgreedTAndC);
                 if(newCOVIDForm != null)
                {
                    JOptionPane.showMessageDialog(this, "Thanks! COVID - 19 self assessment has been submitted for today!");
                }
                else{
                    JOptionPane.showMessageDialog(this, "Some error, please fill the form again");
                }
            }
            catch(Exception ex)
            {
                ex.printStackTrace();
            }
                    }
                }
               }
               catch(Exception ex)
               {
                    
                }
            }
            
        }
        else{
            JOptionPane.showMessageDialog(this, "Please ensure you have agreed terms and conditions before submitting "
                    + "the COVID- 19 Self Assessment form");
        }
    }//GEN-LAST:event_btnSubmitFormActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmitForm;
    private javax.swing.JCheckBox cbAgreeTermsAndConditions;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblConditions;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSignatureDate;
    private javax.swing.JLabel lblSignatureName;
    private javax.swing.JRadioButton rbQOneNo;
    private javax.swing.JRadioButton rbQOneYes;
    private javax.swing.JRadioButton rbQThreeNo;
    private javax.swing.JRadioButton rbQThreeYes;
    private javax.swing.JRadioButton rbQTwoNo;
    private javax.swing.JRadioButton rbQTwoYes;
    private javax.swing.JTextField txtMRN;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSignatureName;
    private javax.swing.JTextField txtTodayDate;
    // End of variables declaration//GEN-END:variables
}
