/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Forms;

import Business.EcoSystem;
import Business.Forms.COVIDSelfDiagnosisForm;
import Business.Patients.Patient;
import Business.UserAccount.UserAccount;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author architnigam
 */
public class COVIDSelfDiagnosisFormJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SelfDiagnosisJPanel
     */
    private UserAccount userAccount;
    private EcoSystem system;
    Patient patientLoggedIn;
    public COVIDSelfDiagnosisFormJPanel(UserAccount userAccount, EcoSystem system) throws ParseException {
        initComponents();
        this.userAccount = userAccount;
        this.system = system;
        patientLoggedIn = system.getPatientDirectory().findPatientByEmailID(userAccount.getUsername(), 
                system.getPatientDirectory().getPatientList());
        
        txtName.setText(patientLoggedIn.getPatientName());
        txtName.setEditable(false);
        
        txtSignatureName.setText(patientLoggedIn.getPatientName());
        txtSignatureName.setEditable(false);
        
        txtMRN.setText(patientLoggedIn.getPatientMRN());
        txtMRN.setEditable(false);
        
        DateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
        Date todayDate = new Date();
        Date todayDateWithZeroTime = formatter.parse(formatter.format(todayDate));  
        txtTodayDate.setText(String.valueOf(todayDateWithZeroTime));
        txtTodayDate.setEditable(false);
        
        ButtonGroup group1 = new ButtonGroup();
        group1.add(rbQOneNo);
        group1.add(rbQOneYes); 
        
        ButtonGroup group2 = new ButtonGroup();
        group2.add(rbQTwoNo);
        group2.add(rbQTwoYes); 
        
        ButtonGroup group3 = new ButtonGroup();
        group3.add(rbQThreeNo);
        group3.add(rbQThreeYes); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeading = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblLocation = new javax.swing.JLabel();
        txtMRN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rbQOneYes = new javax.swing.JRadioButton();
        rbQOneNo = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rbQTwoYes = new javax.swing.JRadioButton();
        rbQTwoNo = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rbQThreeYes = new javax.swing.JRadioButton();
        rbQThreeNo = new javax.swing.JRadioButton();
        lblConditions = new javax.swing.JLabel();
        cbAgreeTermsAndConditions = new javax.swing.JCheckBox();
        txtSignatureName = new javax.swing.JTextField();
        lblSignatureName = new javax.swing.JLabel();
        lblSignatureDate = new javax.swing.JLabel();
        btnSubmitForm = new javax.swing.JButton();
        txtTodayDate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        lblHeading.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblHeading.setText("CORONAVIRUS SELF ASSESSMENT FORM");

        lblName.setText("Name: ");

        lblLocation.setText("MRN:");

        jLabel3.setText("Have you been to one of the COVID-19 affected countries in the last 14 days?");

        rbQOneYes.setText("Yes");

        rbQOneNo.setText("No");

        jLabel4.setText("Have you been in close contact with a confirmed case of coronavirus? ");

        rbQTwoYes.setText("Yes");

        rbQTwoNo.setText("No");

        jLabel5.setText("Are you currently experiencing symptoms (cough, shortness of breath, fever)");

        rbQThreeYes.setText("Yes");

        rbQThreeNo.setText("No");

        lblConditions.setText("By submitting I hereby confirm that the information I have given above is true, and that I will comply with the terms and conditions outlined above. ");

        cbAgreeTermsAndConditions.setText("I agree to terms & conditions. * ");

        lblSignatureName.setText("Name: ");

        lblSignatureDate.setText("Today's Date: ");

        btnSubmitForm.setText("Submit COVID-19 Self Diagnosis Form");
        btnSubmitForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitFormActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/COVID.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jLabel9.setPreferredSize(new java.awt.Dimension(116, 109));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbAgreeTermsAndConditions, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblSignatureName)
                                .addGap(18, 18, 18)
                                .addComponent(txtSignatureName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(lblSignatureDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTodayDate, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblLocation))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMRN, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbQTwoYes, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbQOneYes, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbQOneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbQTwoNo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(33, 33, 33)
                        .addComponent(rbQThreeYes, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rbQThreeNo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblConditions, javax.swing.GroupLayout.PREFERRED_SIZE, 955, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btnSubmitForm, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocation)
                    .addComponent(txtMRN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbQOneYes)
                    .addComponent(rbQOneNo))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rbQTwoYes)
                    .addComponent(rbQTwoNo))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rbQThreeYes)
                    .addComponent(rbQThreeNo))
                .addGap(18, 18, 18)
                .addComponent(lblConditions, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbAgreeTermsAndConditions, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSignatureName)
                    .addComponent(txtSignatureName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSignatureDate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTodayDate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(btnSubmitForm, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitFormActionPerformed
        // TODO add your handling code here:
        boolean hasPatientTraveledAbroad = false;
        boolean hasPatientBeenInContactWithPositivePatient= false;
        boolean isPatientExperiencingSymptoms= false;
        boolean hasPatientAgreedTAndC= false;
        
        if(rbQOneNo.isSelected())
        {
            hasPatientTraveledAbroad = false;
        }
        else if(rbQOneYes.isSelected())
        {
            hasPatientTraveledAbroad = true;
        }
        
        if(rbQTwoNo.isSelected())
        {
            hasPatientBeenInContactWithPositivePatient = false;
        }
        else if(rbQTwoYes.isSelected())
        {
            hasPatientBeenInContactWithPositivePatient = true;
        }
        
        if(rbQThreeNo.isSelected())
        {
            isPatientExperiencingSymptoms = false;
        }
        else if(rbQThreeYes.isSelected())
        {
            isPatientExperiencingSymptoms = true;
        }
        
        if(cbAgreeTermsAndConditions.isSelected())
        {
            hasPatientAgreedTAndC = true;
        }
        else{
            hasPatientAgreedTAndC = false;
        }
        
        
        if(hasPatientAgreedTAndC)
        {
            for(int index = 0; index < system.getCovidFormsDirectory().getListOfCOVIDForms().size(); index++)
            {
                COVIDSelfDiagnosisForm currentCOVIDForm = system.getCovidFormsDirectory().getListOfCOVIDForms().get(index);
                if(currentCOVIDForm.getPatientFillingForm().getPatientMRN().equals(patientLoggedIn.getPatientMRN()))
                {
                    if(currentCOVIDForm.getDateOfForm().equals(new Date()))
                    {
                        JOptionPane.showMessageDialog(this, "COVID - 19 self assessment already submitted for today!");
                    }
                }
            }
            try{
                COVIDSelfDiagnosisForm newCOVIDForm = system.getCovidFormsDirectory().createCOVIDSelfDiagnosisForm(patientLoggedIn, 
                    hasPatientTraveledAbroad, hasPatientBeenInContactWithPositivePatient, isPatientExperiencingSymptoms, 
                    hasPatientAgreedTAndC);
                if(newCOVIDForm != null)
                {
                    JOptionPane.showMessageDialog(this, "Thanks! COVID - 19 self assessment has been submitted for today!");
                }
                else{
                    JOptionPane.showMessageDialog(this, "Some error, please fill the form again");
                }
            }
            catch(Exception ex)
            {
                ex.printStackTrace();
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Please ensure you have agreed terms and conditions before submitting "
                    + "the COVID- 19 Self Assessment form");
        }
    }//GEN-LAST:event_btnSubmitFormActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmitForm;
    private javax.swing.JCheckBox cbAgreeTermsAndConditions;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblConditions;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSignatureDate;
    private javax.swing.JLabel lblSignatureName;
    private javax.swing.JRadioButton rbQOneNo;
    private javax.swing.JRadioButton rbQOneYes;
    private javax.swing.JRadioButton rbQThreeNo;
    private javax.swing.JRadioButton rbQThreeYes;
    private javax.swing.JRadioButton rbQTwoNo;
    private javax.swing.JRadioButton rbQTwoYes;
    private javax.swing.JTextField txtMRN;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSignatureName;
    private javax.swing.JTextField txtTodayDate;
    // End of variables declaration//GEN-END:variables
}
