/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HospiceAdminRole;

import Business.Counsellors.Counsellor;
import Business.Donors.Donor;
import Business.EcoSystem;
import Business.Organization;
import Business.Providers.Provider;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.SystemAdminWorkArea.AddDonorJPanel;
import userinterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;

/**
 *
 * @author rohannayak
 */
public class ManageCounsellorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCounsellorJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    Organization customerOrg;
    EcoSystem system;
    Donor Donor;
    public ManageCounsellorJPanel(JPanel userProcessContainer,UserAccount userAccount, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.system = system;
        this.customerOrg = customerOrg;
        populateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        tblCounsellorList = new javax.swing.JTable();
        lblCounsellorList = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        txtContactNo = new javax.swing.JTextField();
        txtEmailID = new javax.swing.JTextField();
        lblContactNo = new javax.swing.JLabel();
        lblEmailID = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(null);

        tblCounsellorList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Counsellor ID", "Name", "Address", "City", "State", "Zip Code", "Country", "Contact No", "Email Id", "Counsellor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(tblCounsellorList);

        add(jScrollPane);
        jScrollPane.setBounds(161, 138, 690, 115);

        lblCounsellorList.setFont(new java.awt.Font("Helvetica", 1, 13)); // NOI18N
        lblCounsellorList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCounsellorList.setText("Counsellor List");
        add(lblCounsellorList);
        lblCounsellorList.setBounds(161, 106, 109, 26);

        lblTitle.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Manage Counsellor");
        add(lblTitle);
        lblTitle.setBounds(368, 35, 324, 25);

        btnCreate.setFont(new java.awt.Font("Helvetica", 1, 13)); // NOI18N
        btnCreate.setText("Create>>");
        btnCreate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate);
        btnCreate.setBounds(701, 269, 150, 30);

        btnUpdate.setFont(new java.awt.Font("Helvetica", 1, 13)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate);
        btnUpdate.setBounds(332, 269, 93, 30);

        btnDelete.setFont(new java.awt.Font("Helvetica", 1, 13)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(522, 269, 87, 30);

        btnBack.setFont(new java.awt.Font("Helvetica", 1, 13)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backbtnimg-2.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(161, 38, 95, 25);

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CounsellorImage2.png"))); // NOI18N
        add(lblImage);
        lblImage.setBounds(515, 317, 336, 240);

        btnRefresh.setFont(new java.awt.Font("Helvetica", 1, 13)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh);
        btnRefresh.setBounds(161, 269, 104, 30);
        add(txtContactNo);
        txtContactNo.setBounds(283, 330, 214, 26);

        txtEmailID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIDActionPerformed(evt);
            }
        });
        add(txtEmailID);
        txtEmailID.setBounds(283, 362, 214, 26);

        lblContactNo.setFont(new java.awt.Font("Helvetica", 1, 13)); // NOI18N
        lblContactNo.setText("Contact No:");
        add(lblContactNo);
        lblContactNo.setBounds(161, 338, 72, 13);

        lblEmailID.setFont(new java.awt.Font("Helvetica", 1, 13)); // NOI18N
        lblEmailID.setText("Email ID:");
        add(lblEmailID);
        lblEmailID.setBounds(161, 370, 57, 13);

        btnSave.setBackground(new java.awt.Color(166, 158, 200));
        btnSave.setFont(new java.awt.Font("Helvetica", 1, 13)); // NOI18N
        btnSave.setText("Save");
        btnSave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave);
        btnSave.setBounds(208, 406, 86, 33);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
          AddCounsellorJPanel addCounsellorjpanel = new AddCounsellorJPanel(userProcessContainer, userAccount, system);
        userProcessContainer.add("Add Counsellor",addCounsellorjpanel);
        CardLayout Layout = (CardLayout) userProcessContainer.getLayout();
        Layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        

            // TODO add your handling code here:
            //            populateTable();
            //            tblCustomerList.revalidate();
            //            tblCustomerList.repaint();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
                int SelectedRow = tblCounsellorList.getSelectedRow();
        if(SelectedRow < 0)
        {
            JOptionPane.showMessageDialog(null, "Please select a particular row");
            return;
        }
        else
        {
            DefaultTableModel model = (DefaultTableModel) tblCounsellorList.getModel();
            Counsellor selectedcounsellor = (Counsellor) model.getValueAt(SelectedRow, 10);
            system.getProviderDirectory().deleteProvider(SelectedRow);
            JOptionPane.showMessageDialog(this, "Counsellor Details Deleted");
            populateTable();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout Layout = (CardLayout) userProcessContainer.getLayout();
        AdminWorkAreaJPanel a = new AdminWorkAreaJPanel(userProcessContainer, userAccount, system);
        userProcessContainer.add(a);
        Layout.next(userProcessContainer);

        
    }//GEN-LAST:event_btnBackActionPerformed

    public void populateTable()
    {
     
        DefaultTableModel dtm = (DefaultTableModel) tblCounsellorList.getModel();
        dtm.setRowCount(0);
        
        for( Counsellor d : system.getCounsellorDirectory().getListOfCounsellors())
        {
            Object [] row = new Object[10];
            row[0] = d.getCounsellorName();
            row[1] = d.getCounsellorAddress();
            row[2] = d.getCounsellorCity();
            row[3] = d.getCounsellorState();
            row[4] = d.getCounsellorZipCode();
            row[5] = d.getCounsellorCountry();
            row[6] = d.getCounsellorContactNo();
            row[7] = d.getCounsellorEmailID();
            row[8] = d.getOperatingHospice().getHospiceName();
            row[9] = d;
            dtm.addRow(row);
        }
    }
    
    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
  populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int SelectedRow = tblCounsellorList.getSelectedRow();
        if(SelectedRow < 0)
        {
            JOptionPane.showMessageDialog(null, "Please select a particular row");
            return;
        }
        else
        {
            DefaultTableModel model = (DefaultTableModel) tblCounsellorList.getModel();
            Counsellor selectedCounsellor = (Counsellor) model.getValueAt(SelectedRow, 9);
            Counsellor updateCounsellor = system.getCounsellorDirectory().updateCounsellor(selectedCounsellor);
            updateCounsellor.setCounsellorContactNo(txtContactNo.getText());
            updateCounsellor.setCounsellorEmailID(txtEmailID.getText());
            JOptionPane.showMessageDialog(null, "Updates have been saved!!");
            txtContactNo.setText("");
            txtEmailID.setText("");

        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtEmailIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblContactNo;
    private javax.swing.JLabel lblCounsellorList;
    private javax.swing.JLabel lblEmailID;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblCounsellorList;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtEmailID;
    // End of variables declaration//GEN-END:variables
}
