/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Alerts;

import Business.Alerts.Alert;
import Business.EcoSystem;
import Business.Nurses.Nurse;
import Business.Patients.Patient;
import Business.Providers.Provider;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;

/**
 *
 * @author architnigam
 */
public class CreateAnAlertJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateAnAlertJPanel
     */
    UserAccount account;
    EcoSystem system;
    Patient patient;
    Provider reportingProvider;
    public CreateAnAlertJPanel(UserAccount account, EcoSystem system) {
        initComponents();
        this.account = account;
        this.system = system;
        patient = system.getPatientDirectory().findPatientByEmailID(account.getUsername(), 
                system.getPatientDirectory().getPatientList());
        txtMRN.setText(patient.getPatientMRN());
        txtMRN.setEditable(false);
        
        reportingProvider = patient.getRegisteredProvider();
        
        txtReportingProvider.setText(reportingProvider.getProviderName());
        txtReportingProvider.setEditable(false);
        
        checkifPatientHasAnExistingAlertInSystem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMRN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ddSymptom = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtReportingProvider = new javax.swing.JTextField();
        btnAlert = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        jLabel1.setText("Create an Alert");
        add(jLabel1);
        jLabel1.setBounds(250, 40, 270, 80);

        jLabel2.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel2.setText("Patient MRN: ");
        add(jLabel2);
        jLabel2.setBounds(80, 180, 170, 40);

        txtMRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMRNActionPerformed(evt);
            }
        });
        add(txtMRN);
        txtMRN.setBounds(450, 190, 150, 40);

        jLabel3.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel3.setText("Which major symptom are you experiencing?:");
        add(jLabel3);
        jLabel3.setBounds(80, 250, 340, 15);

        ddSymptom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chest pain", "Dizziness", "Increased Heart Rate", "Flu-like symptoms" }));
        add(ddSymptom);
        ddSymptom.setBounds(450, 240, 140, 30);

        jLabel4.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel4.setText("Patient's Reporting Provider:");
        add(jLabel4);
        jLabel4.setBounds(80, 300, 197, 15);
        add(txtReportingProvider);
        txtReportingProvider.setBounds(446, 286, 160, 40);

        btnAlert.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btnAlert.setText("Send an alert ");
        btnAlert.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAlert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlertActionPerformed(evt);
            }
        });
        add(btnAlert);
        btnAlert.setBounds(320, 390, 160, 60);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlertActionPerformed
        // TODO add your handling code here:
        String message = "";
        patient = system.getPatientDirectory().findPatientByEmailID(account.getUsername(), 
                system.getPatientDirectory().getPatientList());
        reportingProvider = patient.getRegisteredProvider();
        String alertReason = ddSymptom.getSelectedItem().toString();
        int alertLevel = 0;
        if(alertReason.equalsIgnoreCase("Flu-like symptoms"))
        {
            alertLevel = 0;
        }
        else if(alertReason.equalsIgnoreCase("Dizziness"))
        {
            alertLevel = 1;    
         }
        else if(alertReason.equalsIgnoreCase("Chest pain") || alertReason.equalsIgnoreCase("Increased Heart Rate"))
        {
            alertLevel = 2;    
        }
        Nurse nurse = system.getNurseDirectory().returnAnOnDutyNurse(system.getNurseDirectory().getNurseList());
        Alert newAlert = system.getAlertsDirectory().createNewAlert(patient, alertReason, alertLevel, reportingProvider, nurse);
        if(newAlert != null)
        {
            if(alertLevel == 1)
            {
                message = "Alert successfully created and status is set to 'Open'! Nurse: " + nurse.getNurseName()+" is on their way"
                        + " for immediate help";
            }
            else if(alertLevel == 2)
            {
                message = "Alert successfully created and status is set to 'Open'!\n\n Ambulance is on the way to "+patient.getPatientAddress()
                        + " for immediate help and your reporting provider Dr. '"+patient.getRegisteredProvider().getProviderName()
                        +"' and nurse '"+nurse.getNurseName()+"'  has been informed.";
            }
            else if(alertLevel == 0)
            {
                message = "Alert successfully created and status is set to 'Open' and sent to your reporting provider Dr. '"+patient.getRegisteredProvider().getProviderName()
                        +"' and nurse '"+nurse.getNurseName()+"\nPlease continue your regular medication.";
            }
            JOptionPane.showMessageDialog(this, message);
            btnAlert.setEnabled(false);
        }
    }//GEN-LAST:event_btnAlertActionPerformed

    private void txtMRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMRNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMRNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlert;
    private javax.swing.JComboBox<String> ddSymptom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtMRN;
    private javax.swing.JTextField txtReportingProvider;
    // End of variables declaration//GEN-END:variables

    private void checkifPatientHasAnExistingAlertInSystem() {
        
        if(system.getAlertsDirectory().doesPatientHaveOneOpenAlertAlreadyInSystem(patient, 
                system.getAlertsDirectory().getListOfAlerts()))
        {
            btnAlert.setEnabled(false);
        }
    }
}
