/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Alerts;

import Business.Alerts.Alert;
import Business.EcoSystem;
import Business.Nurses.Nurse;
import Business.Patients.Patient;
import Business.Providers.Provider;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;

/**
 *
 * @author architnigam
 */
public class CreateAnAlertJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateAnAlertJPanel
     */
    UserAccount account;
    EcoSystem system;
    Patient patient;
    Provider reportingProvider;
    public CreateAnAlertJPanel(UserAccount account, EcoSystem system) {
        initComponents();
        this.account = account;
        this.system = system;
        patient = system.getPatientDirectory().findPatientByEmailID(account.getUsername(), 
                system.getPatientDirectory().getPatientList());
        txtMRN.setText(patient.getPatientMRN());
        txtMRN.setEditable(false);
        
        reportingProvider = patient.getRegisteredProvider();
        
        txtReportingProvider.setText(reportingProvider.getProviderName());
        txtReportingProvider.setEditable(false);
        
        checkifPatientHasAnExistingAlertInSystem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMRN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ddSymptom = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtReportingProvider = new javax.swing.JTextField();
        btnAlert = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("CREATE AN ALERT: ");

        jLabel2.setText("Patient MRN: ");

        jLabel3.setText("Which major symptom are your experiencing?:");

        ddSymptom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chest pain", "Dizziness", "Increased Heart Rate", "Flu-like symptoms" }));

        jLabel4.setText("Patient's Reporting Provider:");

        btnAlert.setText("Send an alert ");
        btnAlert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel2)
                        .addGap(78, 78, 78)
                        .addComponent(txtMRN, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ddSymptom, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtReportingProvider, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAlert))))
                .addContainerGap(409, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMRN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ddSymptom, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtReportingProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(btnAlert)
                .addContainerGap(262, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlertActionPerformed
        // TODO add your handling code here:
        String message = "";
        patient = system.getPatientDirectory().findPatientByEmailID(account.getUsername(), 
                system.getPatientDirectory().getPatientList());
        reportingProvider = patient.getRegisteredProvider();
        String alertReason = ddSymptom.getSelectedItem().toString();
        int alertLevel = 0;
        if(alertReason.equalsIgnoreCase("Flu-like symptoms"))
        {
            alertLevel = 0;
        }
        else if(alertReason.equalsIgnoreCase("Dizziness"))
        {
            alertLevel = 1;    
         }
        else if(alertReason.equalsIgnoreCase("Chest pain") || alertReason.equalsIgnoreCase("Increased Heart Rate"))
        {
            alertLevel = 2;    
        }
        Nurse nurse = system.getNurseDirectory().returnAnOnDutyNurse(system.getNurseDirectory().getNurseList());
        Alert newAlert = system.getAlertsDirectory().createNewAlert(patient, alertReason, alertLevel, reportingProvider, nurse);
        if(newAlert != null)
        {
            if(alertLevel == 1)
            {
                message = "Alert successfully created and status is set to 'Open'! Nurse: " + nurse.getNurseName()+" is on their way"
                        + " for immediate help";
            }
            else if(alertLevel == 2)
            {
                message = "Alert successfully created and status is set to 'Open'!\n\n Ambulance is on the way to "+patient.getPatientAddress()
                        + " for immediate help and your reporting provider Dr. '"+patient.getRegisteredProvider().getProviderName()
                        +"' and nurse '"+nurse.getNurseName()+"'  has been informed.";
            }
            else if(alertLevel == 0)
            {
                message = "Alert successfully created and status is set to 'Open' and sent to your reporting provider Dr. '"+patient.getRegisteredProvider().getProviderName()
                        +"' and nurse '"+nurse.getNurseName()+"\nPlease continue your regular medication.";
            }
            JOptionPane.showMessageDialog(this, message);
            btnAlert.setEnabled(false);
        }
    }//GEN-LAST:event_btnAlertActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlert;
    private javax.swing.JComboBox<String> ddSymptom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtMRN;
    private javax.swing.JTextField txtReportingProvider;
    // End of variables declaration//GEN-END:variables

    private void checkifPatientHasAnExistingAlertInSystem() {
        
        if(system.getAlertsDirectory().doesPatientHaveOneOpenAlertAlreadyInSystem(patient, 
                system.getAlertsDirectory().getListOfAlerts()))
        {
            btnAlert.setEnabled(false);
        }
    }
}
