/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Alerts;

import Business.Alerts.Alert;
import Business.EcoSystem;
import Business.Providers.Provider;
import Business.Role.NurseRole;
import Business.Role.Role;
import Business.Role.Role.RoleType;
import static Business.Role.Role.RoleType.Provider;
import Business.UserAccount.UserAccount;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author architnigam
 */
public class ManageAlertsProviderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAlertsProviderJPanel
     */
    EcoSystem system;
    UserAccount account;
    public ManageAlertsProviderJPanel(EcoSystem system, UserAccount account) {
        initComponents();
        this.system = system;
        this.account = account;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlerts = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        tblAlerts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Alert ID", "Alert Symptom", "Alert Time", "Alert Status"
            }
        ));
        jScrollPane1.setViewportView(tblAlerts);

        add(jScrollPane1);
        jScrollPane1.setBounds(368, 123, 730, 230);

        jButton1.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jButton1.setText("Update");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jButton1);
        jButton1.setBounds(956, 371, 142, 52);

        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        jLabel1.setText("ALERTS ASSIGNED TO ME:");
        add(jLabel1);
        jLabel1.setBounds(368, 68, 239, 43);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/nishitasheelendraupadhyay/Desktop/HospiceCareManagementSystem/src/Images/NurseAlerts.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 1440, 880);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAlerts;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model1 = (DefaultTableModel) tblAlerts.getModel();
        Provider provider = system.getProviderDirectory().findProviderByEmailID(account.getUsername(), 
                system.getProviderDirectory().getProviderList());
        model1.setRowCount(0);
        for(int index = 0; index < system.getAlertsDirectory().getListOfAlerts().size(); index++)
        {
            Object[] row = new Object[4];
            Alert currentAlert = system.getAlertsDirectory().getListOfAlerts().get(index);
            if(currentAlert.getAlertProvider().getProviderNPI().equals(
            provider.getProviderNPI()))
            {
                row[0] = currentAlert.getAlertID();
                row[1] = currentAlert.getAlertSymptom();
                row[2] = currentAlert.getAlertTime();
                row[3] = currentAlert.getAlertStatus();
            }
            model1.addRow(row);
        }
    }
}
