/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Alerts;

import Business.Alerts.Alert;
import Business.EcoSystem;
import Business.LookUpMapping;
import Business.Nurses.Nurse;
import Business.Providers.Provider;
import Business.UserAccount.UserAccount;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author architnigam
 */
public class ManageAlertsNurseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAlertsNurseJPanel
     */
    EcoSystem system;
    UserAccount account;
    LookUpMapping lookups = new LookUpMapping();
    public ManageAlertsNurseJPanel(EcoSystem system, UserAccount account) {
        initComponents();
        this.system = system;
        this.account = account;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlerts = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        jLabel1.setText("Alerts Assigned To Me");
        add(jLabel1);
        jLabel1.setBounds(61, 21, 215, 46);

        tblAlerts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Alert ID", "Patient Name", "Alert Symptom", "Alert Time", "Alert Status", "Alert"
            }
        ));
        jScrollPane1.setViewportView(tblAlerts);

        add(jScrollPane1);
        jScrollPane1.setBounds(70, 90, 770, 224);

        jButton2.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jButton2.setText("Update");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(670, 330, 174, 55);

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/nishitasheelendraupadhyay/Downloads/NurseAlerts.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3);
        jLabel3.setBounds(0, 0, 1440, 880);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAlerts;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model1 = (DefaultTableModel) tblAlerts.getModel();
        Nurse loggedInNurse = system.getNurseDirectory().findNurseByEmailID(account.getUsername(), 
                system.getNurseDirectory().getNurseList());
        model1.setRowCount(0);
        for(int index = 0; index < system.getAlertsDirectory().getListOfAlerts().size(); index++)
        {
            Object[] row = new Object[6];
            Alert currentAlert = system.getAlertsDirectory().getListOfAlerts().get(index);
            if(currentAlert.getAlertNurse().getNurseID().equals(
            loggedInNurse.getNurseID()))
            {
                row[0] = currentAlert.getAlertID();
                row[1] = currentAlert.getAlertPatient().getPatientName();
                row[2] = currentAlert.getAlertSymptom();
                row[3] = currentAlert.getAlertTime();
                String alertStatusValue = lookups.mapAlertStatus(currentAlert.getAlertStatus());
                row[4] = alertStatusValue;
                row[5] = currentAlert;
            }
            model1.addRow(row);
        }
    }
}
