/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FederalAgency;

import Business.Audits.Audit;
import Business.EcoSystem;
import Business.Hospice.Hospice;
import Business.LookUpMapping;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author architnigam
 */
public class FederalAgencyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form 
     */
    JPanel userProcessContainer;
    UserAccount account;
    EcoSystem system;
    public FederalAgencyJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.system = system;
        populateHospiceDropdown();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAudits = new javax.swing.JTable();
        ddHospice = new javax.swing.JComboBox<>();
        btnViewTransactions = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setRequestFocusEnabled(false);
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel1.setText("Select a Hospice: ");
        add(jLabel1);
        jLabel1.setBounds(10, 200, 130, 20);

        tblAudits.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Audit ID", "Transaction Type", "Balance Before Transaction", "Balance After Transaction", "Transaction Time", "Comments"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAudits);

        add(jScrollPane1);
        jScrollPane1.setBounds(6, 260, 1679, 248);

        ddHospice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        ddHospice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddHospiceActionPerformed(evt);
            }
        });
        add(ddHospice);
        ddHospice.setBounds(140, 200, 186, 27);

        btnViewTransactions.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnViewTransactions.setText("View Transactions");
        btnViewTransactions.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewTransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTransactionsActionPerformed(evt);
            }
        });
        add(btnViewTransactions);
        btnViewTransactions.setBounds(350, 200, 132, 21);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/usa.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(15, 6, 209, 169);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/usa.jpeg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setPreferredSize(new java.awt.Dimension(1691, 1179));
        add(jLabel3);
        jLabel3.setBounds(-5, -4, 1370, 1180);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTransactionsActionPerformed
        // TODO add your handling code here:
        LookUpMapping lookups = new LookUpMapping();
        String selectedHospice = ddHospice.getSelectedItem().toString();
        Hospice hospice = system.getHospiceDirectory().findHospiceByName(selectedHospice, 
                system.getHospiceDirectory().getListOfHospice());
         DefaultTableModel model = (DefaultTableModel) tblAudits.getModel();
         model.setRowCount(0);
         Object[] row = new Object[6];
        for(Audit audit : system.getAuditDirectory().getListOfAudits())
        {
            if(audit.getHospice().getHospiceID().equals(hospice.getHospiceID()))
            {
               row[0] = audit.getAuditID();
               String transactionCode = audit.getTransactionType();
               String transactionCodeValue = lookups.MapTransactionCodes(transactionCode);
               row[1] = transactionCodeValue;
               row[2] = "$ "+ audit.getBeforeBalance();
               row[3] = "$ "+ audit.getAfterBalance();
               row[4] = audit.getTimeOfTransaction();
               row[5] = audit.getComments();
               model.addRow(row);
            }
        }
    }//GEN-LAST:event_btnViewTransactionsActionPerformed

    private void ddHospiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddHospiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddHospiceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewTransactions;
    private javax.swing.JComboBox<String> ddHospice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAudits;
    // End of variables declaration//GEN-END:variables

    private void populateHospiceDropdown() {
        for(Hospice hospice : system.getHospiceDirectory().getListOfHospice())
        {
            ddHospice.addItem(hospice.getHospiceName());
        }
    }
}
