/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Hospice.Hospice;
import Business.SetIDsForEnterprises;
import Business.UserAccount.UserAccount;
import Business.ValidationLogic;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author nishitasheelendraupadhyay
 */
public class AddHospiceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddHospiceJPanel
     */
    UserAccount userAccount;
    EcoSystem system;
    JPanel userProcessContainer;
    public AddHospiceJPanel(JPanel userProcessContainer, UserAccount userAccount, EcoSystem system) {
        initComponents();
        this.system = system;
        this.userAccount = userAccount;
        this.userProcessContainer = userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblZipCode = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        lblContactNo = new javax.swing.JLabel();
        lblEmailID = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtZipCode = new javax.swing.JTextField();
        txtCountry = new javax.swing.JTextField();
        txtContactNo = new javax.swing.JTextField();
        txtEmailID = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setForeground(new java.awt.Color(204, 204, 255));
        setLayout(null);

        lbltitle.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        lbltitle.setText("Add Hospice");
        add(lbltitle);
        lbltitle.setBounds(360, 20, 310, 50);

        lblName.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lblName.setText("Name:");
        add(lblName);
        lblName.setBounds(310, 80, 90, 60);

        lblAddress.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lblAddress.setText("Address:");
        add(lblAddress);
        lblAddress.setBounds(310, 150, 62, 15);

        lblCity.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lblCity.setText("City:");
        add(lblCity);
        lblCity.setBounds(310, 250, 32, 15);

        lblState.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lblState.setText("State:");
        add(lblState);
        lblState.setBounds(308, 195, 40, 15);

        lblZipCode.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lblZipCode.setText("Zip Code:");
        add(lblZipCode);
        lblZipCode.setBounds(310, 300, 67, 15);

        lblCountry.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lblCountry.setText("Country:");
        add(lblCountry);
        lblCountry.setBounds(310, 350, 60, 15);

        lblContactNo.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lblContactNo.setText("Contact No:");
        add(lblContactNo);
        lblContactNo.setBounds(290, 460, 82, 15);

        lblEmailID.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lblEmailID.setText("Email ID:");
        add(lblEmailID);
        lblEmailID.setBounds(310, 410, 60, 15);

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        add(txtAddress);
        txtAddress.setBounds(390, 130, 220, 40);

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName);
        txtName.setBounds(389, 84, 220, 40);

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });
        add(txtCity);
        txtCity.setBounds(390, 230, 220, 40);

        txtState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateActionPerformed(evt);
            }
        });
        add(txtState);
        txtState.setBounds(390, 180, 220, 40);
        add(txtZipCode);
        txtZipCode.setBounds(390, 280, 220, 40);
        add(txtCountry);
        txtCountry.setBounds(390, 330, 220, 40);

        txtContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNoActionPerformed(evt);
            }
        });
        add(txtContactNo);
        txtContactNo.setBounds(390, 440, 220, 40);

        txtEmailID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIDActionPerformed(evt);
            }
        });
        add(txtEmailID);
        txtEmailID.setBounds(390, 390, 220, 40);

        btnBack.setBackground(new java.awt.Color(193, 137, 165));
        btnBack.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backbtnimg-2.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(120, 20, 130, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Hospice.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(600, 80, 472, 324);

        btnSave.setBackground(new java.awt.Color(193, 137, 165));
        btnSave.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave);
        btnSave.setBounds(350, 540, 130, 60);
    }// </editor-fold>//GEN-END:initComponents

    private void txtStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNoActionPerformed

    private void txtEmailIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIDActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
         userProcessContainer.remove(this);
        CardLayout Layout = (CardLayout) userProcessContainer.getLayout();
        SystemAdminWorkAreaJPanel a = new SystemAdminWorkAreaJPanel(userProcessContainer, userAccount, system);
        userProcessContainer.add(a);
        Layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        ValidationLogic validationLogic = new ValidationLogic();
         if(validationLogic.validateIfAllFieldsAreFilled_8(txtAddress,txtCity,txtContactNo, txtCountry,txtEmailID,txtName,txtState,txtZipCode))
         {
             String HospiceName = txtName.getText();
             String HospiceAddress = txtAddress.getText();
             String HospiceState = txtState.getText();
             String HospiceCity = txtCity.getText();
             String HospiceZipcode = txtZipCode.getText();
             String HospiceCountry = txtCountry.getText();
             String HospiceEmailID = txtEmailID.getText();
             String HospiceContactNo = txtContactNo.getText();
             
             SetIDsForEnterprises setIDForEnterprises = new SetIDsForEnterprises();
             String HospiceID = setIDForEnterprises.SetIDForHospice();
             
             Hospice Newhospice = system.getHospiceDirectory().createNewHospice(HospiceID, HospiceName, HospiceAddress, HospiceCity, HospiceState, HospiceCountry, HospiceContactNo, HospiceEmailID, HospiceZipcode);
             
             if(Newhospice!= null)
             {
                 JOptionPane.showMessageDialog(this, "Hospice details are saved successfully!!");
                 txtName.setText("");
                 txtAddress.setText("");
                 txtState.setText("");
                 txtCity.setText("");
                 txtZipCode.setText("");
                 txtCountry.setText("");
                 txtEmailID.setText("");
                 txtContactNo.setText("");
             }
             else
             {
                 JOptionPane.showMessageDialog(this, "Hospice details not saved successfully!");
             }
         }
         else
         {
             JOptionPane.showMessageDialog(this, "Please ensure that all fields are filled!!");
         }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblContactNo;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblEmailID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtEmailID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables
}
