/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Donors.Donor;
import Business.EcoSystem;
import Business.Hospice.Hospice;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nishitasheelendraupadhyay
 */
public class ManageHospiceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageHospiceJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    EcoSystem ecosystem;
    public ManageHospiceJPanel(JPanel userProcessContainer, UserAccount userAccount, EcoSystem ecosystem) {
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.ecosystem = ecosystem;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DonorScrollPane = new javax.swing.JScrollPane();
        tblHospiceList = new javax.swing.JTable();
        lblHospiceList = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblimage = new javax.swing.JLabel();
        txtContactNo = new javax.swing.JTextField();
        txtEmailID = new javax.swing.JTextField();
        lblContactNo = new javax.swing.JLabel();
        lblEmailID = new javax.swing.JLabel();
        btnSaveUpdates = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(null);

        tblHospiceList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address", "City", "State", "Zip code", "Country", "Contact No.", "Email ID", "Hospice"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DonorScrollPane.setViewportView(tblHospiceList);

        add(DonorScrollPane);
        DonorScrollPane.setBounds(160, 150, 690, 115);

        lblHospiceList.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lblHospiceList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospiceList.setText("Hospice List");
        add(lblHospiceList);
        lblHospiceList.setBounds(150, 110, 109, 26);

        lblTitle.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Manage Hospice");
        add(lblTitle);
        lblTitle.setBounds(372, 30, 370, 60);

        btnBack.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(170, 40, 90, 40);

        btnRefresh.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh);
        btnRefresh.setBounds(160, 280, 110, 40);

        btnUpdate.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate);
        btnUpdate.setBounds(338, 280, 100, 40);

        btnCreate.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnCreate.setText("Create >>");
        btnCreate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate);
        btnCreate.setBounds(718, 280, 130, 40);

        btnDelete.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(550, 280, 100, 40);

        lblimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/HospiceManage.png"))); // NOI18N
        add(lblimage);
        lblimage.setBounds(460, 360, 733, 278);

        txtContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNoActionPerformed(evt);
            }
        });
        add(txtContactNo);
        txtContactNo.setBounds(270, 360, 120, 40);
        add(txtEmailID);
        txtEmailID.setBounds(270, 410, 120, 40);

        lblContactNo.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lblContactNo.setText("Contact No. : ");
        add(lblContactNo);
        lblContactNo.setBounds(150, 380, 130, 15);

        lblEmailID.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lblEmailID.setText("Email ID : ");
        add(lblEmailID);
        lblEmailID.setBounds(150, 430, 110, 15);

        btnSaveUpdates.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnSaveUpdates.setText("Save");
        btnSaveUpdates.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSaveUpdates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveUpdatesActionPerformed(evt);
            }
        });
        add(btnSaveUpdates);
        btnSaveUpdates.setBounds(210, 510, 130, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout Layout = (CardLayout) userProcessContainer.getLayout();
        SystemAdminWorkAreaJPanel a = new SystemAdminWorkAreaJPanel(userProcessContainer, userAccount, ecosystem);
        userProcessContainer.add(a);
        Layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    public void populateTable()
    {
     
        DefaultTableModel dtm = (DefaultTableModel) tblHospiceList.getModel();
        dtm.setRowCount(0);
        
        for(Hospice d : ecosystem.getHospiceDirectory().getListOfHospice())
        {
            Object [] row = new Object[9];
            row[0] = d.getHospiceName();
            row[1] = d.getHospiceAddress();
            row[2] = d.getHospiceCity();
            row[3] = d.getHospiceState();
            row[4] = d.getHospiceZipCode();
            row[5] = d.getHospiceCountry();
            row[6] = d.getHospiceContactNumber();
            row[7] = d.getHospiceEmailID();
            row[8] = d;
            dtm.addRow(row);
        }
        

    }
    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int SelectedRow = tblHospiceList.getSelectedRow();
        if(SelectedRow < 0)
        {
            JOptionPane.showMessageDialog(null, "Please select a particular row");
            return;
        }
        else
        {
            DefaultTableModel model = (DefaultTableModel) tblHospiceList.getModel();
            Hospice selectedHospice = (Hospice) model.getValueAt(SelectedRow, 8);
            
            txtContactNo.setText(selectedHospice.getHospiceContactNumber());
            txtEmailID.setText(selectedHospice.getHospiceEmailID());
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        AddHospiceJPanel addhospicejpanel = new AddHospiceJPanel(userProcessContainer, userAccount, ecosystem);
        userProcessContainer.add("Add Hospice",addhospicejpanel);
        CardLayout Layout = (CardLayout) userProcessContainer.getLayout();
        Layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int SelectedRow = tblHospiceList.getSelectedRow();
        if(SelectedRow < 0)
        {
            JOptionPane.showMessageDialog(this, "Please select a particular row");
            return;
        }
        else 
        {
            DefaultTableModel model = (DefaultTableModel) tblHospiceList.getModel();
            Hospice selectedClaim = (Hospice) model.getValueAt(SelectedRow, 8);
            ecosystem.getHospiceDirectory().deleteHospice(SelectedRow);
            JOptionPane.showMessageDialog(this, "Hospice Details Deleted");
            populateTable();
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNoActionPerformed

    private void btnSaveUpdatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveUpdatesActionPerformed
        // TODO add your handling code here:
        int SelectedRow = tblHospiceList.getSelectedRow();
        if(SelectedRow < 0)
        {
            JOptionPane.showMessageDialog(null, "Please select a particular row");
            return;
        }
        else
        {
            DefaultTableModel model = (DefaultTableModel) tblHospiceList.getModel();
            Hospice selectedHospice  = (Hospice) model.getValueAt(SelectedRow, 8); 
            Hospice updatehospice = ecosystem.getHospiceDirectory().updateHospice(selectedHospice);
            updatehospice.setHospiceContactNumber(txtContactNo.getText());
            updatehospice.setHospiceEmailID(txtEmailID.getText());
            JOptionPane.showMessageDialog(null, "Updates have been saved!!");
            txtContactNo.setText("");
            txtEmailID.setText("");
        }
        
    }//GEN-LAST:event_btnSaveUpdatesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane DonorScrollPane;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSaveUpdates;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblContactNo;
    private javax.swing.JLabel lblEmailID;
    private javax.swing.JLabel lblHospiceList;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblimage;
    private javax.swing.JTable tblHospiceList;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtEmailID;
    // End of variables declaration//GEN-END:variables
}
