/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.SystemAdminWorkArea;

import Business.ClaimsBilling.Claim;
import Business.Donors.Donor;
import Business.Donors.DonorsDirectory;
import Business.EcoSystem;
import Business.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JPanel;;
import Business.EcoSystem;
import Business.Hospice.Hospice;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author nishitasheelendraupadhyay
 */
public class ManageDonorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDonorJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    Organization customerOrg;
    EcoSystem system;
    Donor Donor;
    public ManageDonorJPanel(JPanel userProcessContainer, UserAccount userAccount, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.system = system;
        this.customerOrg = customerOrg;
         populateTable();
    }
    //public void populateTable();
    //{
        
    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DonorScrollPane = new javax.swing.JScrollPane();
        tblDonorList = new javax.swing.JTable();
        lblDonorList = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblimage = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEmailID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSaveUpdates = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(null);

        tblDonorList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Email ID", "Donor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DonorScrollPane.setViewportView(tblDonorList);

        add(DonorScrollPane);
        DonorScrollPane.setBounds(140, 150, 690, 115);

        lblDonorList.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lblDonorList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDonorList.setText("Donor List");
        add(lblDonorList);
        lblDonorList.setBounds(120, 120, 109, 26);

        lblTitle.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Manage Donors");
        add(lblTitle);
        lblTitle.setBounds(400, 20, 270, 70);

        btnBack.setBackground(new java.awt.Color(193, 137, 165));
        btnBack.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backbtnimg-2.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(140, 30, 90, 40);

        btnRefresh.setBackground(new java.awt.Color(193, 137, 165));
        btnRefresh.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh);
        btnRefresh.setBounds(140, 280, 110, 50);

        btnUpdate.setBackground(new java.awt.Color(193, 137, 165));
        btnUpdate.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate);
        btnUpdate.setBounds(340, 280, 100, 50);

        btnCreate.setBackground(new java.awt.Color(193, 137, 165));
        btnCreate.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnCreate.setText("Create >>");
        btnCreate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate);
        btnCreate.setBounds(708, 280, 120, 50);

        btnDelete.setBackground(new java.awt.Color(193, 137, 165));
        btnDelete.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(540, 280, 100, 50);

        lblimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manageDonorimg.png"))); // NOI18N
        add(lblimage);
        lblimage.setBounds(490, 250, 510, 450);

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName);
        txtName.setBounds(280, 370, 120, 40);
        add(txtEmailID);
        txtEmailID.setBounds(280, 420, 120, 40);

        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 13)); // NOI18N
        jLabel1.setText("Name:");
        add(jLabel1);
        jLabel1.setBounds(180, 390, 50, 20);

        jLabel2.setFont(new java.awt.Font("Helvetica", 1, 13)); // NOI18N
        jLabel2.setText("Email ID:");
        add(jLabel2);
        jLabel2.setBounds(176, 426, 80, 30);

        btnSaveUpdates.setBackground(new java.awt.Color(193, 137, 165));
        btnSaveUpdates.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnSaveUpdates.setText("Save");
        btnSaveUpdates.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSaveUpdates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveUpdatesActionPerformed(evt);
            }
        });
        add(btnSaveUpdates);
        btnSaveUpdates.setBounds(220, 480, 100, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout Layout = (CardLayout) userProcessContainer.getLayout();
        SystemAdminWorkAreaJPanel a = new SystemAdminWorkAreaJPanel(userProcessContainer, userAccount, system);
        userProcessContainer.add(a);
        Layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed
    public void populateTable()
    {
     
        DefaultTableModel dtm = (DefaultTableModel) tblDonorList.getModel();
        dtm.setRowCount(0);
        
        for(Donor d : system.getDonorDirectory().getListOfDonors())
        {
            Object [] row = new Object[4];
            row[0] = d.getDonorID();
            row[1] = d.getDonorName();
            row[2] = d.getDonorEmailID();
            row[3] = d;
            dtm.addRow(row);
        }
        

    }
    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int SelectedRow = tblDonorList.getSelectedRow();
        if(SelectedRow < 0)
        {
            JOptionPane.showMessageDialog(null, "Please select a particular row");
            return;
        }
        else
        {
            DefaultTableModel model = (DefaultTableModel) tblDonorList.getModel();
            Donor selectedDonor  = (Donor) model.getValueAt(SelectedRow, 3);
           
            txtName.setText(selectedDonor.getDonorName());
            txtEmailID.setText(selectedDonor.getDonorEmailID());
            
            //populateTable();

            
        }
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        AddDonorJPanel adddonorjpanel = new AddDonorJPanel(userProcessContainer, userAccount, system);
        userProcessContainer.add("Add Donor",adddonorjpanel);
        CardLayout Layout = (CardLayout) userProcessContainer.getLayout();
        Layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int SelectedRow = tblDonorList.getSelectedRow();
        if(SelectedRow < 0)
        {
            JOptionPane.showMessageDialog(this, "Please select a particular row");
            return;
        }
        else 
        {
            DefaultTableModel model = (DefaultTableModel) tblDonorList.getModel();
            Donor selectedClaim = (Donor) model.getValueAt(SelectedRow, 3);
            system.getDonorDirectory().deleteDonor(SelectedRow);
            JOptionPane.showMessageDialog(this, "Donor Details Deleted");
            populateTable();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnSaveUpdatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveUpdatesActionPerformed
        // TODO add your handling code here:
        int SelectedRow = tblDonorList.getSelectedRow();
        if(SelectedRow < 0)
        {
            JOptionPane.showMessageDialog(null, "Please select a particular row");
            return;
        }
        else
        {
            DefaultTableModel model = (DefaultTableModel) tblDonorList.getModel();
            Donor selectedDonor  = (Donor) model.getValueAt(SelectedRow, 3); 
            Donor updatedonor = system.getDonorDirectory().updateDonor(selectedDonor);
            updatedonor.setDonorName(txtName.getText());
            updatedonor.setDonorEmailID(txtEmailID.getText());
            JOptionPane.showMessageDialog(null, "Updates have been saved!!");
            txtName.setText("");
            txtEmailID.setText("");
        }
    }//GEN-LAST:event_btnSaveUpdatesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane DonorScrollPane;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSaveUpdates;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblDonorList;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblimage;
    private javax.swing.JTable tblDonorList;
    private javax.swing.JTextField txtEmailID;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
