/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Notes;

import Business.EcoSystem;
import Business.Observation.Observation;
import Business.UserAccount.UserAccount;

/**
 *
 * @author architnigam
 */
public class NotesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NotesJPanel
     */
    UserAccount account;
    EcoSystem system;
    public NotesJPanel(UserAccount account, EcoSystem system) {
        initComponents();
        this.account = account;
        this.system = system;
        txtMRN.setEditable(false);
        txtPatientD.setEditable(false);
        txtPatientM.setEditable(false);
        txtObservations.setEditable(false);
        populateMeetingIDDropdown();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ddMeetingID = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtMRN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPatientD = new javax.swing.JTextField();
        txtPatientM = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservations = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 20)); // NOI18N
        jLabel1.setText("Meeting Notes:");
        add(jLabel1);
        jLabel1.setBounds(249, 40, 379, 78);

        jLabel2.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel2.setText("Select Meeting ID: ");
        add(jLabel2);
        jLabel2.setBounds(80, 170, 128, 15);

        ddMeetingID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        add(ddMeetingID);
        ddMeetingID.setBounds(274, 159, 200, 44);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch);
        btnSearch.setBounds(492, 167, 120, 29);

        jLabel3.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel3.setText("MRN: ");
        add(jLabel3);
        jLabel3.setBounds(108, 265, 41, 15);
        add(txtMRN);
        txtMRN.setBounds(276, 255, 192, 36);

        jLabel4.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel4.setText("Was patient depressed?");
        add(jLabel4);
        jLabel4.setBounds(43, 348, 190, 20);

        jLabel5.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel5.setText("Was patient taking their medications?");
        add(jLabel5);
        jLabel5.setBounds(14, 438, 260, 15);

        jLabel6.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel6.setText("Observations:");
        add(jLabel6);
        jLabel6.setBounds(62, 509, 97, 15);
        add(txtPatientD);
        txtPatientD.setBounds(276, 339, 192, 34);
        add(txtPatientM);
        txtPatientM.setBounds(276, 428, 181, 37);

        txtObservations.setColumns(20);
        txtObservations.setRows(5);
        jScrollPane1.setViewportView(txtObservations);

        add(jScrollPane1);
        jScrollPane1.setBounds(276, 509, 362, 148);

        jLabel7.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/notes.jpeg"))); // NOI18N
        jLabel7.setText("jLabel7");
        add(jLabel7);
        jLabel7.setBounds(0, 0, 990, 730);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String meetingID = ddMeetingID.getSelectedItem().toString();
        String depressionValue = "";
        String medicationValue = "";
        for(int index = 0; index < system.getObservationDirectory().getObservationList().size(); index++)
        {
            Observation observation = system.getObservationDirectory().getObservationList().get(index);
            if(observation.getMeetingID().equals(meetingID))
            {
                txtMRN.setText(observation.getPatientName().getPatientMRN());
                if(observation.isIsPatientDepressed())
                {
                    depressionValue = "Yes";
                }
                else{
                    depressionValue = "False";
                }
                txtPatientD.setText(depressionValue);
                if(observation.isIsPatientTakingMedications())
                {
                    medicationValue = "Yes";
                }
                else{
                    medicationValue = "No";
                }
                txtPatientM.setText(medicationValue);
                txtObservations.setText(observation.getObservationComments());
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> ddMeetingID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtMRN;
    private javax.swing.JTextArea txtObservations;
    private javax.swing.JTextField txtPatientD;
    private javax.swing.JTextField txtPatientM;
    // End of variables declaration//GEN-END:variables

    private void populateMeetingIDDropdown() {
        for(int index = 0; index < system.getObservationDirectory().getObservationList().size(); index++)
        {
            Observation observation = system.getObservationDirectory().getObservationList().get(index);
            ddMeetingID.addItem(observation.getMeetingID());
        }
    }
}
