/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DonorRole;

import Business.Appointments.Appointment;
import Business.Counsellors.Counsellor;
import Business.Donation.Donation;
import Business.Donors.Donor;
import Business.EcoSystem;
import Business.LookUpMapping;
import Business.UserAccount.UserAccount;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author architnigam
 */
public class MyDonationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MyDonationJPanel
     */
    UserAccount userAccount;
     EcoSystem system;
    public MyDonationJPanel(UserAccount userAccount, EcoSystem system) {
        initComponents();
        this.userAccount = userAccount;
        this.system = system;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMyDonations = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 20)); // NOI18N
        jLabel1.setText("My Donations:");

        tblMyDonations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Donation ID", "Hospice", "Donation Amount", "Donation Date"
            }
        ));
        jScrollPane1.setViewportView(tblMyDonations);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(438, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMyDonations;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model1 = (DefaultTableModel) tblMyDonations.getModel();
        LookUpMapping lookups = new LookUpMapping();
        Donor donor = system.getDonorDirectory().findDonorByEmailID(userAccount.getUsername(), 
                 system.getDonorDirectory().getListOfDonors());
        model1.setRowCount(0);
        for(int index = 0; index < system.getDonationDirectory().getDonationList().size(); index++)
        {
            Object[] row = new Object[4];
            Donation currentDonation = system.getDonationDirectory().getDonationList().get(index);
            if(currentDonation.getDonor().getDonorID().equals(
            donor.getDonorID()))
            {
                row[0] = currentDonation.getDonationID();
                row[1] = currentDonation.getHospiceToWhichAmountIsDonated().getHospiceName();
                row[2] = currentDonation.getDonationAmount();
                row[3] = currentDonation.getDateOfDonation();
            }
            model1.addRow(row);
        }
    }
}
